name: etl_project
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - ansi2html=1.9.1
  - anyio=4.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=24.3.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - binaryornot=0.4.4
  - blas=1.0
  - bleach=6.2.0
  - blinker=1.9.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.1.31
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.3.1
  - cookiecutter=2.6.0
  - cookiecutter-data-science=2.0.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dash=2.14.2
  - dash-bootstrap-components=1.7.1
  - dash-core-components=2.0.0
  - dash-daq=0.5.0
  - dash-html-components=2.0.0
  - dash_colorscales=0.0.4
  - dataframe_image=0.1.1
  - dbus=1.13.18
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dtale=3.16.1
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - expat=2.6.4
  - flask=3.0.3
  - flask-compress=1.13
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.12.1
  - frozenlist=1.5.0
  - future=1.0.0
  - ghp-import=2.1.0
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.14.0
  - hatchling=1.27.0
  - httpcore=1.0.2
  - httpx=0.27.0
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.5.0
  - importlib_resources=6.5.2
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.8.1
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.3.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.11.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=17.2
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - lz4=4.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - mergedeep=1.3.4
  - missingno=0.4.2
  - mistune=2.0.4
  - mkdocs=1.6.1
  - mkdocs-get-deps=0.2.0
  - mkdocs-material=9.5.50
  - mkdocs-material-extensions=1.3.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - multidict=6.1.0
  - mysql=8.4.0
  - nbclassic=1.1.0
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nltk=3.9.1
  - notebook=7.3.2
  - notebook-shim=0.2.3
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openpyxl=3.1.5
  - openssl=3.4.0
  - overrides=7.4.0
  - packaging=24.2
  - paginate=0.5.7
  - pandas=2.2.3
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pathspec=0.12.1
  - patsy=0.5.6
  - pcre2=10.42
  - pexpect=4.8.0
  - pillow=11.1.0
  - pip=24.2
  - platformdirs=3.10.0
  - plotly=5.24.1
  - pluggy=1.5.0
  - ply=3.11
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - propcache=0.2.0
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.12.8
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python-tzdata=2023.3
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyyaml-env-tag=0.1
  - pyzmq=26.2.0
  - qgrid=1.3.1
  - qt-main=5.15.2
  - qtconsole=5.6.1
  - qtpy=2.4.1
  - readline=8.2
  - referencing=0.30.2
  - regex=2024.11.6
  - requests=2.32.3
  - retrying=1.3.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rpds-py=0.22.3
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - seaborn=0.13.2
  - send2trash=1.8.2
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - squarify=0.4.3
  - stack_data=0.2.0
  - statsmodels=0.14.4
  - strsimpy=0.1.9
  - tbb=2021.8.0
  - tenacity=9.0.0
  - terminado=0.17.1
  - text-unidecode=1.3
  - threadpoolctl=3.5.0
  - tinycss2=1.2.1
  - tk=8.6.14
  - tomli=2.2.1
  - tornado=6.4.2
  - tqdm=4.66.5
  - traitlets=5.14.3
  - trove-classifiers=2024.10.14
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=15.1.0
  - unidecode=1.3.8
  - urllib3=2.3.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.0.6
  - wheel=0.44.0
  - widgetsnbextension=3.6.6
  - xarray=2024.11.0
  - xlrd=2.0.1
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.18.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - blis==1.2.0
      - catalogue==2.0.10
      - chardet==5.2.0
      - cloudpathlib==0.20.0
      - confection==0.1.5
      - cymem==2.0.11
      - en-core-web-sm==3.8.0
      - langcodes==3.5.0
      - language-data==1.3.0
      - marisa-trie==1.2.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - murmurhash==1.0.12
      - preshed==3.0.9
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pymdown-extensions==10.14.1
      - python-slugify==8.0.4
      - shellingham==1.5.4
      - smart-open==7.1.0
      - spacy==3.8.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - thinc==8.3.4
      - typer==0.15.1
      - types-python-dateutil==2.9.0.20241206
      - wasabi==1.1.3
      - watchdog==6.0.0
      - weasel==0.4.1
      - wordcloud==1.9.4
      - wrapt==1.17.2
